### PR TITLE
Modified to allowing searching postcodes as well as placenames

### PR DESCRIPTION
**Pull request by yemling**
Uses https://secure.geonames.org/postalCodeSearchJSON and a few if
statements with radio buttons to choose a placename or postcode and
build the url appropriately.

### CODE REVIEW

**Comment by yemling** [comment]
Ah, I think I did it!!!

**Comment by yemling** [comment]
I meant to say that the only bit that annoyed me was being able to get the value of the locationType radio box using document.getElementsByName. I just couldn't figure it out hence there being two very similar functions right next to each other.

**Comment by brendan-ward** [comment]
@yemling is it important that the user have the option of searching place names OR postal codes, or is this something that can be configured by the developer based on the application.  E.g., configuring the plugin so that it allows you to search postal codes instead of placenames.

**Comment by yemling** [comment]
My client asked for both in this case.
Cheers
Gemma Nash

________________________________

**Comment by brendan-ward** [comment]
@yemling is it important that the user choose?  Or can the developer set things up so that both endpoints are automatically searched, perhaps in part depending on the content?

E.g., If user enters 12345, we detect that it is a number and search against postal codes.  Otherwise, for all strings, we search against the main search endpoint.

What I'm trying to understand is if there is a way to avoid the UI for choosing one or other of the options.

**Comment by yemling** [comment]
I thought about that but couldn't figure it out because uk postcodes are alphanumeric.
If you can do it,  that'd be great.
Thanks
Gemma Nash

________________________________

**Comment by brendan-ward** [comment]
@yemling I'm not keen on adding extra user interface for choosing postal codes or place names by default.  It's too bad that Geonames service doesn't give us a single endpoint and the ability to pass in extra things to search against.

The solution I'm mulling over now is to add a couple of parameters to the options instead:
* `includePostalCodes` (or similar): boolean, `false` by default, but `true` when you want to search against postal codes
* `postalCodesRegex`: a regex pattern to determine if the string passed by the user is a postal code, and if so, search using the postal codes geonames service instead of the default.  Since this regex will need to vary by country, I am thinking of including a couple available options for US and UK postal codes that the developer can select, or they can write their own.

Looking at UK and US postal codes, I see low likelihood of confusing those with placename searches: they always have numbers and follow a consistent pattern.  (other countries make this much more difficult, e.g., Canada)

This gets us to the point where the user interface is the same as it is now (simple) but the developer has better ability to control when names or postal codes are queried.

Does that sound like a reasonable solution to you?

**Comment by yemling** [comment]
Hi.
that all sounds great. I find regex difficult,  but if you can do it that's brilliant.
Thanks and let me know if I can help anymore.
Gemma Nash

________________________________

**Comment by brendan-ward** [comment]
@yemling I made the above changes.  See example of how to use this here:
https://github.com/consbio/Leaflet.Geonames/blob/master/examples/postCodes.html#L61-L62

I tested with UK postcodes found on https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom
And they returned appropriate looking results.

If you test this and it doesn't return the expected results, first look at your network requests in your browser's dev tools.  It will fall back to searching the default Geonames API if the regex for postcodes does not succeed.

**Pull request merged**
